blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='post_list'),
	url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='post_detail'),
	url(r'^post/(?P<pk>[0-9]+)/$', views.previous_post, name='previous_post'),
	url(r'^post/(?P<pk>[0-9]+)/$', views.next_post, name='next_post'),
	url(r'^post/new/$', views.post_new, name='post_new'),
	url(r'^post/(?P<pk>[0-9]+)/edit/$', views.post_edit, name='post_edit'),
	url(r'^post/draft/$', views.post_draft_list, name='post_draft_list'),
	url(r'^post/(?P<pk>[0-9]+)/publish/$', views.post_publish, name='post_publish'),
	url(r'^post/(?P<pk>[0-9]+)/delete/$', views.post_delete, name='post_delete'),
	url(r'^post/(?P<pk>[0-9]+)/add_comment/$', views.add_comment, name='add_comment'),
	url(r'^comment/(?P<pk>[0-9]+)/approve/$', views.approve_comment, name='approve_comment'),
	url(r'^comment/(?P<pk>[0-9]+)/remove/$', views.remove_comment, name='remove_comment'),
	url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
	url(r'^tag/(?P<pk>[0-9]+)/$', views.TagsView.as_view(), name='tag_detail'),
	url(r'^search/$', views.search, name='search'),
	url(r'^register/$', views.register, name='register'),
	url(r'^profile/$', views.user_profile, name='user_profile'),
	url(r'^profile/edit/$', views.profile_edit, name='profile_edit'),
	url(r'^ajax/validate_username/$', views.validate_username, name='validate_username'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib.auth.models import User
from django.contrib import admin
from rest_framework import routers, serializers, viewsets
from django.contrib.auth import views as auth_view
from blog.models import Post, Tag, Comment
from rest_framework_swagger.views import get_swagger_view
#from django_registration.backends.one_step import RegistrationView

class UserSerializer(serializers.HyperlinkedModelSerializer):
	class Meta:
		model = User
		fields = ('url', 'username', 'email', 'is_staff')

class UserViewSet(viewsets.ModelViewSet):
	queryset = User.objects.all()
	serializer_class = UserSerializer

class PostSerializer(serializers.HyperlinkedModelSerializer):
	class Meta:
		model = Post
		fields = ('title', 'author', 'text', 'created_date', 'published_date', 'views')

class PostViewSet(viewsets.ModelViewSet):
	queryset = Post.objects.all()
	serializer_class = PostSerializer

class TagSerializer(serializers.HyperlinkedModelSerializer):
	class Meta:
		model = Tag
		fields = ('name',)

class TagViewSet(viewsets.ModelViewSet):
	queryset = Tag.objects.all()
	serializer_class = TagSerializer

class CommentSerializer(serializers.HyperlinkedModelSerializer):
	class Meta:
		model = Comment
		fields = ('post', 'author', 'text', 'created_date')

class CommentViewSet(viewsets.ModelViewSet):
	queryset = Comment.objects.all()
	serializer_class = CommentSerializer

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'post', PostViewSet)
router.register(r'tag', TagViewSet)
router.register(r'comment', CommentViewSet)

schema_view = get_swagger_view(title='djangocoder API')

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(router.urls)),
#   url(r'^accounts/register/', RegistrationView.as_view(), name='django_registration_register'),
#   url(r'^accounts/', include('django_registration.backends.one_step.urls')),
#   url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/login/', auth_view.LoginView.as_view(), name='login'),
    url(r'^accounts/logout/', auth_view.LogoutView.as_view(next_page='/'), name='logout'),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'', include('blog.urls')),
    url(r'^schema/', schema_view),
    #url(r'^search/', include('haystack.urls')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth.models import (
	BaseUserManager, AbstractBaseUser
)

class Tag(models.Model):
	name = models.CharField(max_length=100)

	def get_absolute_url(self):
		return reverse('tag_detail', kwargs={'pk':self.pk})

	def __str__(self):
		return self.name

class Post(models.Model):
	title = models.CharField(max_length=200)
	author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
	img_link = models.CharField(default='/static/images/tide.jpeg', max_length=255)
	text = models.TextField()
	created_date = models.DateTimeField(default=timezone.now)
	published_date = models.DateTimeField(blank=True, null=True)
	views = models.PositiveIntegerField(default=0)
	tags = models.ManyToManyField(Tag, blank=True)

	def publish(self):
		self.published_date = timezone.now()
		self.save()

	def increase_views(self):
		self.views = self.views + 1
		self.save(update_fields=['views'])

	def get_absolute_url(self):
		return reverse('post_detail', kwargs={'pk':self.pk})

	def __str__(self):
		return self.title

class Comment(models.Model):
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	level = models.PositiveIntegerField(default=0)

class MyUser(AbstractBaseUser):
	age = models.PositiveIntegerField(default=0)

blog/forms.py
from django import forms

from .models import Post, Comment
from django.contrib.auth.models import User

class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ('title', 'tags', 'img_link', 'text')

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('text',)

class ProfileForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ('first_name', 'last_name', 'email')

blog/views.py
import markdown

from django.shortcuts import render, get_object_or_404, redirect, HttpResponse
from django.utils import timezone
from .models import Post, Comment, Tag
from django.contrib.auth.models import User
from .forms import PostForm, CommentForm, ProfileForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import ListView, DetailView
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import Http404, JsonResponse
from django.contrib.admin.views.decorators import staff_member_required

class IndexView(ListView):
	model = Post
	template_name = 'blog/home.html'
	context_object_name = 'posts'
	paginate_by = 2

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		paginator = context.get('paginator')
		page = context.get('page_obj')
		is_paginated = context.get('is_paginated')
		pagination_data = self.pagination_data(paginator, page, is_paginated)
		context.update(pagination_data)
		return context

	def pagination_data(self, paginator, page, is_paginated):
		if not is_paginated:
			return {}
		left = []
		right = []
		left_has_more = False
		right_has_more = False
		first = False
		last = False
		page_number = page.number
		total_pages = paginator.num_pages
		page_range = paginator.page_range
		if page_number == 1:
			right = page_range[page_number:page_number +2]
			if right[-1] < total_pages - 1:
				right_has_more = True
			if right[-1] < total_pages:
				last = True
		elif page_number == total_pages:
			left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0: page_number - 1]
			if left[0] > 2:
				left_has_more = True
			if left[0] > 1:
				first = True
		else:
			left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
			right = page_range[page_number:page_number + 2]
			if right[-1] < total_pages - 1:
				right_has_more = True
			if right[-1] < total_pages:
				last = True
			if left[0] > 2:
				left_has_more = True
			if left[0] > 1:
				first = True
		data = {
			'left': left,
			'right': right,
			'left_has_more': left_has_more,
			'right_has_more': right_has_more,
			'first': first,
			'last': last,
			'page_range': page_range,
		}
		return data
"""
def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'blog/post_list.html', {'posts': posts})
"""

class PostDetailView(DetailView):
	model = Post
	template_name = 'blog/post_detail.html'
	context_object_name = 'post'

	def get(self, request, *args, **kwargs):
		response = super(PostDetailView, self).get(request, *args, **kwargs)
		self.object.increase_views()
		return response

	def get_object(self, queryset=None):
		post = super(PostDetailView, self).get_object(queryset=None)
		post.text = markdown.markdown(post.text,
									extensions=[
										'markdown.extensions.extra',
	                                    'markdown.extensions.codehilite',
	                                    'markdown.extensions.toc',
	                                    ])
		return post

	def get_context_data(self, **kwargs):
		context = super(PostDetailView, self).get_context_data(**kwargs)
		kwargs['form'] = CommentForm()
		return context


def previous_post(request, pk):
	post = get_object_or_404(Post, pk=pk)
	prev_post = post.filter(pk__lt=post.pk)[0:1]
	return render(request, 'blog/post_detail', {'prev_post':prev_post})

def next_post(request, pk):
	post = get_object_or_404(Post, pk=pk)
	next_post = post.filter(pk__gt=post.pk)[0:1]
	return render(request, 'blog/post_detail', {'next_post':next_post})

@login_required
def post_new(request):
	if request.user.is_staff or request.user.is_superuser:
		if request.method == 'POST':
			form = PostForm(request.POST)
			if form.is_valid():
				post = form.save(commit=False)
				post.author = request.user
				#post.published_date = timezone.now()
				post.save()
				return redirect('post_detail', pk=post.pk)
		else:
			form = PostForm()
	else:
		raise Http404
	return render(request, 'blog/post_new.html',{'form': form})

@login_required
def post_edit(request, pk):
	if request.user.is_staff or request.user.is_superuser:
		post = get_object_or_404(Post, pk=pk)
		if request.method == "POST":
			form = PostForm(request.POST, instance=post)
			if form.is_valid():
				post = form.save(commit=False)
				post.author = request.user
				#post.published_date = timezone.now()
				post.save()
				return redirect('post_detail', pk=post.pk)
		else:
			form = PostForm(instance=post)
	else:
		raise Http404
	return render(request, 'blog/post_edit.html',{'form': form})

@staff_member_required
def post_draft_list(request):
	posts = Post.objects.filter(published_date__isnull=True).order_by('created_date')
	return render(request, 'blog/post_list.html', {'posts': posts})

@staff_member_required
def post_publish(request, pk):
	post = get_object_or_404(Post,pk=pk)
	post.published_date = timezone.now()
	post.save()
	return redirect('post_detail', pk=post.pk)

@staff_member_required
def post_delete(request, pk):
	post = get_object_or_404(Post, pk=pk)
	post.delete()
	redirect('post_list')

@login_required
def add_comment(request, pk):
	"""
	if request.is_ajax():
		data = request.POST
		new_user = request.user
		new_text = data.get('text')
		the_post = Post.objects.get(pk=pk)
		new_comment = Comment(post=the_post, author=new_user, text=new_text)

	"""
	post = Post.objects.get(pk=pk)
	if request.method == "POST":
		form = CommentForm(request.POST)
		#return HttpResponse(form.errors)
		#print(form.errors)
		if form.is_valid():
			#return HttpResponse(form.is_valid())
			comment = form.save(commit=False)
			comment.author = request.user
			comment.created_date = timezone.now()
			comment.post = post
			#comment.text = form.text
			#comment.approve()
			comment.save()
			return redirect('post_detail', pk=post.pk)	
	else:
		#return HttpResponse(request.method)
		form = CommentForm()
	return render(request, 'blog/add_comment.html', {'form': form})


@staff_member_required
def approve_comment(request,pk):
	comment = get_object_or_404(Comment, pk=pk)
	post = comment.post
	comment.approve()
	return redirect('post_detail',pk=post.pk)

@staff_member_required
def remove_comment(request,pk):
	comment = get_object_or_404(Comment, pk=pk)
	post = comment.post
	comment.delete()
	return redirect('post_detail',pk=post.pk)

class ArchivesView(ListView):
	model = Post
	template_name = 'blog/post_list.html'
	context_object_name = 'posts'
	paginate_by = 2;

	def get_queryset(self):
		year = self.kwargs.get('year')
		month = self.kwargs.get('month')
		return super(ArchivesView, self).get_queryset().filter(created_date__year=year,
									created_date__month=month,
									).order_by('-created_date')
"""
def archives(request, year, month):
	post_list = Post.objects.filter(created_date__year=year,
									created_date__month=month,
									).order_by('-created_date')
	return render(request, 'blog/post_list.html', {'posts':post_list})
"""
class TagsView(ListView):
	model = Post
	template_name = 'blog/post_list.html'
	context_object_name = 'posts'
	paginate_by = 2

	def get_queryset(self):
		tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
		return super(TagsView, self).get_queryset().filter(tags__name=tag.name).order_by('-created_date')
"""
def tag_detail(request, pk):
	tag = get_object_or_404(Tag, pk=pk)
	post_list = Post.objects.filter(tags__name=tag.name)
	return render(request, 'blog/post_list.html', {'posts':post_list})
"""
def search(request):
	q = request.GET.get('q')
	error_msg = ''

	if not q:
		error_msg = "Please enter the key word"
		return render(request, 'blog/post_list.html', {'error_msg':error_msg})
	posts = Post.objects.filter(Q(title__icontains=q) | Q(text__icontains=q))
	return render(request, 'blog/post_list.html', {'error_msg':error_msg, 'posts':posts})

def register(request):
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			new_user = form.save()
			#new_user.groups.add(guest)
			return redirect('login')
	else:
		form = UserCreationForm()
	return render(request, 'registration/registration_form.html', {'form': form})

@login_required
def user_profile(request):
	user = request.user
	return render(request, 'blog/user_profile.html', {'user': user})

@login_required
def profile_edit(request):
	user = request.user
	if request.method == "POST":
		form = ProfileForm(request.POST, instance=user)
		if form.is_valid():
			user = form.save(commit=False)
			user.save()
			return redirect('user_profile')
	else:
		form = ProfileForm(instance=user)
	return render(request, 'blog/profile_edit.html', {'form': form})

def validate_username(request):
	username = request.GET.get('username', None)
	data = {
		'is_taken': User.objects.filter(username__iexact=username).exists()
	}
	if data['is_taken']:
		data['error_message'] = 'A user with this username already exists.'
	return JsonResponse(data)

blog/templates/blog/add_comment.html
{% extends 'blog/base.html' %}
{% block content %}
<div>
	<form action="" method="POST">
		{% csrf_token %}
		{{ form.text }}
		<div style = "text-align: center;">
			<button id="push-com" class="btn btn-primary" type="submit">Comment</button>
		</div>
	</form>
</div>
{% endblock %}

blog/templates/blog/base.html
<!doctype html>
{% load staticfiles %}
{% load blog_tags %}
<html lang="en">
 	<head>
	    <!-- Required meta tags -->
	    <meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	    <!-- Bootstrap CSS -->
	    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
	    <link href="{% static 'styles/blog.css' %}" rel="stylesheet" style="text/css">
	    <title>djangocoder</title>
	</head>
	<body>
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
			<a class="navbar-brand" href="/">DJ BLOG</a>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
			    <ul id="nav-left" class="navbar-nav mr-auto">
			        <li class="nav-item active">
			        	<a class="nav-link" href="{% url 'post_list' %}">HOME <span class="sr-only">(current)</span></a>
			        </li>
			        {% if user.is_authenticated %}
			        	{% if user.is_staff or user.is_superuser %}
					        <li class="nav-item">
					        	<a class="nav-link" href="{% url 'post_new' %}">WRITE</a>
					      	</li>
					       	<li class="nav-item">
					        	<a class="nav-link" href="{% url 'post_draft_list' %}">DRAFT</a>
					      	</li>
					    {% endif %}
			        {% else %}
			      		<li class="nav-item">
				        	<a class="nav-link" href="{% url 'login' %}">LOGIN</a>
				      	</li>
			      		<li class="nav-item">
				        	<a class="nav-link" href="{% url 'register' %}">REGISTER</a>
				      	</li>
				    {% endif %}
			    </ul>
			    <form class="form-inline my-2 my-lg-0" role="search" method="get" id="searchform" action="{% url 'search' %}">
			    	
				       	<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
				       	<input src="{% static 'images/search.jpeg' %}" width="30px" height="30px" style="border-radius: 10%" type="image">
			       
			       	<!--
			       	<button type="submit" class="btn btn-outline-warning btn-sm my-2 my-sm-0">Search</button>
			   		-->
			    </form>
			    {% if user.is_authenticated %}
			    <div class="nav-user nav-item dropdown">
        			<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color:white">
          				{{ user.username }}
        			</a>
			        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
			          	<a class="dropdown-item" href="{% url 'user_profile' %}">Profile</a>
			          	<a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
			        </div>
			    </div>
			    {% endif %}
			  </div>
		</nav>
<div>
		<div class="sidebar-container">
			<div class="sidebar" align="left">
				<div class="widget">
					<div class="widget-title">
						<h3>Author</h3>
					</div>
					<ul id="sidebar-author" style="padding-left:5%">
						<li>Michael Dai</li>
						<li>HDU</li>
						{% total_visits as visits_count %}
						<li>visits: {{ visits_count }}</li>
					</ul>
				</div>
			</div>
			<div class="sidebar" align="left">
				<div class="widget widget-recent-posts" align="left">
					<div class="widget-title">
						<h3>Latest</h3>
					</div>
				    {% get_recent_posts as recent_post_list %}
			    	<ul style="padding-left:5%">
			    	{% for post in recent_post_list %}
			    		<li>
			    			<a class="sidebar-link" href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a>
			    		</li>
			    	{% empty %}
			    		no post!
			    	{% endfor %}
			  		</ul>
				</div>
				<div class="widget widget-archives" align="left">
					<div class="widget-title">
						<h3>Archives</h3>
					</div>
				    {% archives as date_list %}
			    	<ul style="padding-left:5%">
			    	{% for date in date_list %}
			    		<li>
			      			<a class="sidebar-link" href="{% url 'archives' date.year date.month %}">{{ date.year }}-{{ date.month }}</a>
			    		</li>
			    	{% empty %}
			    		no archive!
			    	{% endfor %}
			  		</ul>
				</div>
				<div class="widget widget-tags" align="left">
					<div class="widget-title">
						<h3>Tags</h3>
					</div>
				    {% tags as tag_list %}
			    	<ul style="padding-left:0">
			    	{% for tag in tag_list %}
			    		<div>
			    			<a href="{% url 'tag_detail' pk=tag.pk%}" class="badge badge-pill badge-warning">{{ tag.name }} </a>
			    		</div>
			    	{% empty %}
			    		no tags!
			    	{% endfor %}
			  		</ul>
				</div>				
			</div>
		</div>

		<div class="container col-lg-9">
			{% block carousel %}
			{% endblock %}
			{% block content %}
			{% endblock %}
		</div>
<!--
		<footer>
			Powered by Django
		</footer>
-->
</div>
	<!--
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
-->
	<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  </body>
</html>

blog/templates/blog/home.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block carousel %}
	<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
	  	<ol class="carousel-indicators">
	    	<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
	    	<li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
	    	<li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
	  	</ol>
	  	<div class="carousel-inner">
	    	<div class="carousel-item active">
	      	<img class="d-block w-100" src="{% static 'images/tide.jpeg' %}" alt="First slide">
	    	</div>
	    	<div class="carousel-item">
	      		<img class="d-block w-100" src="{% static 'images/red.jpeg' %}" alt="Second slide">
	    	</div>
	    	<div class="carousel-item">
	      		<img class="d-block w-100" src="{% static 'images/lake.jpeg' %}" alt="Third slide">
	    	</div>
	    </div>
		<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
	    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
	    <span class="sr-only">Previous</span>
		</a>
		<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
	    	<span class="carousel-control-next-icon" aria-hidden="true"></span>
	    	<span class="sr-only">Next</span>
		</a>
	</div>
{% endblock %}
{% block content %}
	<div class="row">
		{% if error_msg %}
			<p>{{ error_msg }}</p>
		{% endif %}
		<div class="summary-list">
			{% for post in posts %}
			<div class="media p-2 p-lg-3">
				<div class="media-body">
					<div>
						<div class="text-muted mb-2 f-12">
							<span>{{ post.author }}</span>
							<span>
								{{ post.published_date }}
							</span>
							<span>{{ post.views }} view{{ post.views|pluralize }}</span>
							<span>{{ post.comments.count }} comment{{ post.comments.count|pluralize }}</span>
						</div>
						<div id="post-image">
							<img src="{{ post.img_link }}" width="200px" height="100px" alt="image">
						</div>
						<div id="post-content">
							<h2 class="mt-0 font-weight-bold text-info f-17">
								<a class="post-title" href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a>
							</h2>
							<p class="d-block d-sm-none mb-2 f-15">{{ post.text|linebreaks|truncatechars:54 }}</p>
							<a class="more-link" href="{% url 'post_detail' pk=post.pk %}">More</a>
						</div>
					</div>
				</div>
			</div>
			{% empty %}
				<p>No post currently!</p>
			{% endfor %}
			
			<div class="text-xs-center">
				<ul class="pagination justify-content-center">
				    {% for i in page_range %}
				    	<li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
				    {% endfor %}
				</ul>
			</div>
		</div>
	</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block content %}
	
		<div class="blog col-lg-11">
			<div id="post-head">
				<nav aria-label="breadcrumb">
				    <ol class="breadcrumb">
				        <li class="breadcrumb-item"><a href="/">Home</a></li>
				        <li class="breadcrumb-item active" aria-current="page">{{ post.title }}</li>
				    </ol>
				</nav>
				{% if post.published_date %}
					<p>{{ post.published_date }}</p>
				{% else %}
				<div>
					<a href="{% url 'post_publish' pk=post.pk %}">
						<input type="button" class="btn btn-primary" value="Publish"/>
					</a>
				</div>
				{% endif %}
				<span>{{ post.views }} view{{ post.views|pluralize }}</span>  
				<span>{{ post.comments.count }} comment{{ post.comments.count|pluralize }}</span>
			</div>
			<div class="post-detail-image">
				<img src="{{ post.img_link }}" alt="images">
			</div>
			<h1>{{ post.title }}</h1>
			<p>{{ post.text|safe|linebreaksbr }}</p>
			<div class = "badge-list">
				{% for tag in post.tags.all %}
					<a href="{% url 'tag_detail' pk=tag.pk%}" class="badge badge-pill badge-warning">{{ tag.name }} </a>
				{% endfor %}
			</div>
			{% if user.is_authenticated %}
				{% if user.is_staff or user.is_superuser %}
					<a href="{% url 'post_edit' pk=post.pk %}">
						<input class="btn btn-primary" type="button" value="Edit"/>
					</a>
					<a href="{% url 'post_delete' pk=post.pk %}">
						<input class="btn btn-danger" type="button" value="Delete"/>
					</a>
				{% endif %}
			{% endif %}
			<a href="{% url 'add_comment' pk=post.pk %}">
				<input class="btn btn-primary" type="button" value="Comment"/>
			</a>
			<div>
				<a class="my-page-link" href="/post/{{ prev_post.pk }}/">previous</a>
				<a class="my-page-link" href="/post/{{ next_post.pk }}/">next</a>
			</div>
		</div>
		<div class="comment-list col-lg-11">
			<div class="comment-title">
				<p>COMMENT</p>
			</div>
			{% for comment in post.comments.all %}
				{% if user.is_authenticated or comment.approved_comment %}
				<div class="comment">
					<p class="text-muted mb-2 f-12">
					{{ comment.author }} {{ comment.created_date }}
					{% if not comment.approved_comment and user.is_staff %}
						<a href="{% url 'remove_comment' pk=comment.pk %}">
							<input class="btn btn-outline-danger btn-sm" type="button" value="Remove"/>
						</a>
					{% endif %}						
					</p>
					<p>{{ comment.text|linebreaks }}</p>
				</div>
				{% endif %}
			{% empty %}
				<p>No comments here yet:(</p>
			{% endfor %}
		</div>
	
{% endblock %}